### ISSUE TITLE
Different Blob mime?

### ISSUE THREAD

**Issue by Jaspur** [Lorti/vue-dictaphone#2]
Hi @Lorti, how to change to format/mime of the Blob? It returns a "webm" but I want a mp3 or AAC, so non-chrome browsers can play the audio too.

**Comment by Lorti** [comment]
Hey @Jaspur, this is not possible right now, but we should definitely add the possibility to change the MIME type!

Feel free to open up a pull request, if you want. If not I’ll try to add this feature in the next couple of days.

**Comment by Jaspur** [comment]
Hi @Lorti, I tried to fix it, but couldn't figure out how ;-) So would be great if you'll add the feature!

**Comment by Lorti** [comment]
I've published a new version where you can pass a MIME type prop. There's an example in the README.md.

**Comment by Jaspur** [comment]
Thnx!

**Comment by Jaspur** [comment]
Hmm, still getting the response of a 'video/webm' mime and .webm file extension when submitting the file to the server and fetch the info of the file.

**Comment by Lorti** [comment]
You have to provide some context: What you are trying to achieve? What browser you are using? What server you are using?

Also have you tried setting the type to `audio/mp3` and then save the file via the audio controls in the browser? That should work, if not, the problem may be in your server's code or configuration.

**Comment by manonthemat** [comment]
I'm getting Ogg (Opus) as a default. While I really like that format, Safari doesn't play it. Changing the type to `audio/webm` or `audio/mp3` does not have any effect.

**Comment by manonthemat** [comment]
I get different mime types depending on the browser.
I like ogg, but I unfortunately found out a little too late that it's not supported in Safari.

So I'm trying to get an mp3.

This is what I'm doing now.
(Replacing `audio/mpeg` with `audio/mp3` has the same effect)

```
<vue-dictaphone
  @stop="handleRecording($event)"
  v-slot="{ isRecording, startRecording, stopRecording }"
  mime-type="audio/mpeg"
>
```

My important part of the function who handles the upload of the blob looks like this:

```
      const { authorName, title, part, paragraph } = this;
      const file = new File(
        [this.blob],
        `${authorName}_${title}_${part}_${paragraph}_${Date.now()}.mp3`,
        { type: 'audio/mpeg' }
      );  
      let formData = new FormData();
      formData.append(
        'data',
        JSON.stringify({ authorName, title, part, paragraph })
      );  
      formData.append('myFile', file);
      await apiService.uploadRecording(formData);
```

What happens is that I end up with either a audio/ogg file (firefox) or a video/webm file (chromium).
None of which can be played in Safari.

**Comment by Lorti** [comment]
Hi Matthias, 

I fear that there's only so much you can do about what media type any given browser supports. This varies not only between browsers but also operating systems. 
If you want to deliver an mp3 to all browsers I think your best bet would be to convert your recordings to mp3 files on the server. Sorry that I can't be of more help to you in this regard.

I also took a quick look at your uploading example and tried it myself. I was wondering why you're creating a new file object? I have no trouble uploading an mp3 in Firefox, simply by using the blob directly:

```
      const formData = new FormData();
      formData.append('myRecording.mp3', blob);
      const request = new XMLHttpRequest();
      request.open('POST', 'http://127.0.0.1');
      request.send(formData);
```

**Comment by manonthemat** [comment]
Thanks for catching that. It seems like converting the recordings on the server will be the way to move forward then.
